config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "books#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :books do
    resources :comments, module: :books
  end
  resources :reports do
    resources :comments, module: :reports
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]
  get "timeline", to: "timeline#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :comments, as: :commentable
end

app/controllers/books/comments_controller.rb
# frozen_string_literal: true

class Books::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Book.find(params[:book_id])
    end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.page(params[:page])
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to @book, notice: t("flash.create", model: @book.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: t("flash.update", model: @book.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: t("flash.destroy", model: @book.model_name.human)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, html: {name: "book"}) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t("Editing Book") %></h1>

<%= render "form", book: @book %>

<%= link_to t("link.Show"), @book %> |
<%= link_to t("link.Back"), books_path %>

app/views/books/index.html.erb
<h1><%= t("Books") %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th><%= Book.human_attribute_name(:picture) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.user.name, user_path(book.user) %></td>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= book.author %></td>
        <td><%= book.picture %></td>
        <td><%= link_to t("link.Show"), book %></td>
        <% if book.user == current_user %>
          <td><%= link_to t("link.Edit"), edit_book_path(book) %></td>
          <td><%= link_to t("link.Destroy"), book, method: :delete, data: { confirm: t("alert.sure") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @books %>
<br>
<%= link_to t("link.New Book"), new_book_path %>

app/views/books/new.html.erb
<h1><%= t("New Book") %></h1>

<%= render "form", book: @book %>

<%= link_to t("link.Back"), books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= User.human_attribute_name(:name) %>:</strong>
  <%= link_to @book.user.name, user_path(@book.user) %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:title) %>:</strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:memo) %>:</strong>
  <%= @book.memo %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:author) %>:</strong>
  <%= @book.author %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:picture) %>:</strong>
  <%= image_tag(@book.picture_url) if @book.picture.present? %>
</p>

<% if @book.user == current_user %>
  <%= link_to t("link.Edit"), edit_book_path(@book) %> |
<% end %>
<%= link_to t("link.Back"), books_path %>

<%= render "comments/comments", commentable: @book %>
<%= render "comments/form", commentable: @book %>