config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "books#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :books do
    resources :comments, module: :books
  end
  resources :reports do
    resources :comments, module: :reports
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]
  get "timeline", to: "timeline#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
end

app/controllers/reports/comments_controller.rb
# frozen_string_literal: true

class Reports::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      @commentable = Report.find(params[:report_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  def index
    @reports = Report.page(params[:page])
  end

  # GET /reports/1
  def show
    @report = Report.find(params[:id])
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id
    if @report.save
      redirect_to @report, notice: t("flash.create", model: @report.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("flash.update", model: @report.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    if @report.destroy
      redirect_to reports_url, notice: t("flash.destroy", model: @report.model_name.human)
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:title, :body)
    end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true, html: {name: "report"}) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1><%= t("Editing Report") %></h1>

<%= render "form", report: @report %>

<%= link_to t("link.Show"), @report %> |
<%= link_to t("link.Back"), reports_path %>

app/views/reports/index.html.erb
<h1><%= t("Reports") %></h1>

<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= Report.human_attribute_name(:title) %></th>
      <th><%= Report.human_attribute_name(:body) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.user.name, user_path(report.user) %></td>
        <td><%= report.title %></td>
        <td><%= report.body %></td>
        <td><%= link_to t("link.Show"), report %></td>
        <% if report.user == current_user %>
          <td><%= link_to t("link.Edit"), edit_report_path(report) %></td>
          <td><%= link_to t("link.Destroy"), report, method: :delete, data: { confirm: t("alert.sure") } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @reports %>
<br>
<%= link_to t("link.New Report"), new_report_path %>

app/views/reports/new.html.erb
<h1><%= t("New Report") %></h1>

<%= render "form", report: @report %>

<%= link_to t("link.Back"), reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Report.human_attribute_name(:title) %>:</strong>
  <%= @report.title %>
</p>

<p>
  <strong><%= Report.human_attribute_name(:body) %>:</strong>
  <%= @report.body %>
</p>

<%= link_to t("link.Edit"), edit_report_path(@report) %> |
<%= link_to t("link.Back"), reports_path %>

<%= render "comments/comments", commentable: @report %>
<%= render "comments/form", commentable: @report %>