config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "books#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :books do
    resources :comments, module: :books
  end
  resources :reports do
    resources :comments, module: :reports
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]
  get "timeline", to: "timeline#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p>
    <% if user_signed_in? %>
      <%= link_to t("Books"), books_path %>
      <%= link_to t("Reports"), reports_path %>
      <%= link_to t("My Timeline"), timeline_path %> |
      <%= t("Logged in as") %> <strong><%= link_to current_user.name, user_path(current_user) %></strong>
      <%= link_to t("Edit profile"), edit_user_registration_path %> |
      <%= link_to t("Logout"), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t("Sign up"), new_user_registration_path  %> |
      <%= link_to t("Sign in with GitHub"), user_github_omniauth_authorize_path %> |
      <%= link_to t("Login"), new_user_session_path %>
    <% end %>
  </p>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>